version: "4"
services:
  Baapjiispam25:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      SUDO: $SUDO
      STRING: $STRING
      STRING2: $STRING2
      STRING3: $STRING3
      STRING4: $STRING4
      STRING5: $STRING5
      STRING6: $STRING6
      STRING7: $STRING7
      STRING8: $STRING8
      STRING9: $STRING9
      STRING10: $STRING10
      STRING11: $STRING11
      STRING12: $STRING12
      STRING13: $STRING13
      STRING14: $STRING14
      STRING15: $STRING15
      STRING16: $STRING16
      STRING17: $STRING17
      STRING18: $STRING18
      STRING19: $STRING19
      STRING20: $STRING20
      STRING21: $STRING21
      STRING22: $STRING22
      STRING23: $STRING23
      STRING24: $STRING24
      STRING25: $STRING25
